# Session 22: Additional Exercise - Raghunath

#### Use scikit learn’s Decision Tree class to model and make predictions on the car acceptability using the following dataset:
http://archive.ics.uci.edu/ml/datasets/Car+Evaluation

#### Accuracy metric of the model and predictions using the model on the test set. Also using graphviz, plot the tree

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
#from pandas import Series, DataFrame
#from pylab import rcParams
from sklearn import tree
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pydotplus
import collections
#from sklearn.metrics import classification_report

In [2]:
headers = ['buying','maint','doors','persons','lug_boot','safety', 'car_accept']
cars_data = pd.read_csv("car.data", names=headers, skipinitialspace=True)

In [3]:
cars_data.head()

buying  maint doors persons lug_boot safety car_accept
0  vhigh  vhigh     2       2    small    low      unacc
1  vhigh  vhigh     2       2    small    med      unacc
2  vhigh  vhigh     2       2    small   high      unacc
3  vhigh  vhigh     2       2      med    low      unacc
4  vhigh  vhigh     2       2      med    med      unacc

In [4]:
cars_data.count()

buying        1728
maint         1728
doors         1728
persons       1728
lug_boot      1728
safety        1728
car_accept    1728
dtype: int64

In [5]:
cars_data.describe()

buying maint doors persons lug_boot safety car_accept
count    1728  1728  1728    1728     1728   1728       1728
unique      4     4     4       3        3      3          4
top       low   low     2       2    small    low      unacc
freq      432   432   432     576      576    576       1210

In [6]:
cars_data.car_accept.unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [7]:
cars_data.isna().sum()

buying        0
maint         0
doors         0
persons       0
lug_boot      0
safety        0
car_accept    0
dtype: int64

In [8]:
for c in cars_data.columns:
    print(cars_data[c].unique())

['vhigh' 'high' 'med' 'low']
['vhigh' 'high' 'med' 'low']
['2' '3' '4' '5more']
['2' '4' 'more']
['small' 'med' 'big']
['low' 'med' 'high']
['unacc' 'acc' 'vgood' 'good']


In [9]:
#attributes = {'vhigh': 5, 'high': 4, 'med': 3, 'low': 2, 'small': 1, 'big': 6, 'more': 7, '5more': 8}

In [10]:
ordered_price_attribute = {'low':0,'med':1,'high':2,'vhigh':3}
cars_data['buying'] = [ordered_price_attribute[item] for item in cars_data['buying']] 
cars_data['maint'] = [ordered_price_attribute[item] for item in cars_data['maint']] 

In [11]:
ordered_lug_boot_attribute = {'small':0, 'med':1, 'big':2}
cars_data['lug_boot'] = [ordered_lug_boot_attribute[item] for item in cars_data['lug_boot']] 

In [12]:
ordered_safety_attribute = {'low':0, 'med':1, 'high':2}
cars_data['safety'] = [ordered_safety_attribute[item] for item in cars_data['safety']] 

In [13]:
cars_data.doors.replace('5more', 5, inplace=True)
cars_data.persons.replace('more', 6, inplace=True)

In [14]:
for c in cars_data.columns:
    print(cars_data[c].unique())

[3 2 1 0]
[3 2 1 0]
['2' '3' '4' 5]
['2' '4' 6]
[0 1 2]
[0 1 2]
['unacc' 'acc' 'vgood' 'good']


In [15]:
X = cars_data[['buying','maint','doors','persons','lug_boot','safety']]
y = cars_data['car_accept']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
decision_tree = DecisionTreeClassifier() 
decision_tree.fit(X_train, y_train)  
Y_pred = decision_tree.predict(X_test)  
acc_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)
acc_decision_tree

100.0

In [18]:
acc_decision_tree_test = round(decision_tree.score(X_train, y_train) * 100, 2)
acc_decision_tree_test

100.0

<img src="tree.png" size="500px"/>